### ISSUE TITLE
Passing an array of values for recorder.maxSegmentDuration

### ISSUE THREAD

**Issue by credo92** [hilalbaig/HBRecorder#5] opened 2017-08-29 13:52 UTC
How to pass an array of values like [ 2,4,6,8 ] where each element of array represents a segment duration ( recorder.maxSegmentDuration)

**Comment by hilalbaig** [comment] 2017-08-29 13:58
How can one assign `array` to an `int` type property. If you see maxSegmentDuration property is clearly declared as int. The issue is already referred and closed in #4. I think there is no need to have new opening for it again.

**Comment by credo92** [comment] 2017-08-29 14:15
Yeah i understand. But i wanted to have different segment durations rather than having a uniform one. What if we try to change the type of recorder.maxSegmentDuration to an array type in HBRecorder.h and modify checkMaxSegmentDuration function to take an array in HBRecorder.m, do you think it will work ?

**Comment by hilalbaig** [comment] 2017-08-29 14:20
Then If user set [10,5,15] maximum 3 segments will be recorded?

**Comment by credo92** [comment] 2017-08-29 14:25
yes, in this case , 3 segments will be there  , each having a recorder.maxSegmentDuration of 10 seconds, 5 seconds and 15 seconds.  while, sum of these individual recorder.maxSegmentDurations should be <= recorder.maxDuration property.

**Comment by hilalbaig** [comment] 2017-08-29 15:28
It will produce certain confusions and conflicts with other defined properties such as maxRecordDuration and maxSegmentDuration. We can do one thing to have multiple HBRecorder convenient initilizers, which will define recorder types. Can you work on it?(as i am busy in some work these days) I will create milestone for that and will merge it to master upon completion.

**Comment by credo92** [comment] 2017-08-29 15:32
Yes, I ll try to work it out by doing some refactoring. And will revert in this thread. Thanks.

**Comment by credo92** [comment] 2017-09-01 03:13
I changed maxSegmentDuration in HBRecorder.h, maxSegmentDuration in HBRecorder.m, NOT ABLE TO find some openings Please help.

```
@property (assign, nonatomic) NSArray *maxSegmentDuration;

-(void)checkMaxSegmentDuration:(SCRecorder *)recorder {
    for (int i = 0; i < [_maxSegmentDuration count]; i++)
    {
        
    if([_maxSegmentDuration objectAtIndex:i]) {
        CMTime suggestedMaxSegmentDuration = CMTimeMake([_maxSegmentDuration objectAtIndex:i], 1);
        if (CMTIME_IS_VALID(suggestedMaxSegmentDuration)) {
            if (CMTIME_COMPARE_INLINE(recorder.session.currentSegmentDuration, >=, suggestedMaxSegmentDuration)) {
                [_recorder pause];
                [self.recBtn setImage:self.recStartImage forState:UIControlStateNormal];
            }
        }
    }
   
  }
}
```

I pass maxSegmentDuration an array of different segment durations.
`recorder?.maxSegmentDuration = [ 3,3,3,3,3,3,2,2,2,2,2,1,1 ];
`

**Comment by hilalbaig** [comment] 2017-09-05 07:32
:) It wouldn't work like that. You need to call `checkMaxSegmentDuration`  for each segment then comparing segment duration with passed array.

**Comment by hilalbaig** [comment] 2017-09-05 07:33
I'm closing this issue because it is out of scope for current project.

**Closed as completed by hilalbaig** 2017-09-05 07:33 UTC
Labels: enhancement, invalid
